# Generated by Django 5.0.11 on 2025-01-30 00:41

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_layer_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestauthentication',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=512)),
        ),
    ]
