# Generated by Django 5.0.11 on 2025-02-21 09:01

import django.core.files.storage
import spatial_layer_monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_layer_monitor', '0003_remove_spatialmonitor_destination_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialmonitorhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/data/data/projects/spatial-layer-monitor/private-media'), upload_to=spatial_layer_monitor.models.to_history_images),
        ),
    ]
